### ISSUE TITLE
How do I get the mod

### ISSUE THREAD

**Issue by T3chn3tium** [igoro00/not-as-easy-villagers#4]
I do not know who GitHub works I just want the .jar file please

**Comment by igoro00** [comment]
Github can be confusing for newcomers

1. go to the releases section
![image](https://user-images.githubusercontent.com/35789870/159577554-69471818-9351-4ee6-8d29-b0afc88530fa.png)
2. Download the .jar
![image](https://user-images.githubusercontent.com/35789870/159577686-e702955b-f415-44da-90bf-0ec2da5300db.png)

Also, as it stated in the readme, it requires fabric-api and fabric-language-kotlin mods
